// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./nav";
import Script from "next/script";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Further Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
       <Script id="gtmId" strategy="afterInteractive">{`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-K673G6TM')`}</Script>
      </head>
      <body>
        <noscript>
          <iframe 
          src="https://www.googletagmanager.com/ns.html?id=GTM-K673G6TM"
          height="0" 
          width="0" 
          style={{display: "none", visibility: "hidden"}}></iframe>
          </noscript>
        <Nav></Nav>
        {children}
      </body>
    </html>
  );
}
